# Generated by Django 3.0.8 on 2020-09-03 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthplace',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='child',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple children.', null=True, related_name='_customuser_child_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cousin',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple cousins.', null=True, related_name='_customuser_cousin_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple parents.', null=True, related_name='_customuser_parent_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sibling',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple siblings.', null=True, related_name='_customuser_sibling_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='married_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
