# Generated by Django 3.0.8 on 2020-09-03 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200903_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='child',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple children.', related_name='_customuser_child_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cousin',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple cousins.', related_name='_customuser_cousin_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parent',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple parents.', related_name='_customuser_parent_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sibling',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple siblings.', related_name='_customuser_sibling_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
