# Generated by Django 3.0.8 on 2020-09-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200903_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthday',
            new_name='date_of_birth',
        ),
    ]
