# Generated by Django 3.0.8 on 2020-09-03 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200903_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='child',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cousin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sibling',
        ),
        migrations.AddField(
            model_name='customuser',
            name='aunts_and_uncles',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple.', related_name='_customuser_aunts_and_uncles_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple.', related_name='_customuser_children_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cousins',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple.', related_name='_customuser_cousins_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='neices_and_nephews',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple.', related_name='_customuser_neices_and_nephews_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple.', related_name='_customuser_parents_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='siblings',
            field=models.ManyToManyField(blank=True, help_text='Hold Ctrl + Click to choose multiple.', related_name='_customuser_siblings_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthplace',
            field=models.CharField(help_text='City, State', max_length=255, null=True),
        ),
    ]
