# Generated by Django 3.0.8 on 2020-09-04 17:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200903_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='aunts_and_uncles',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='children',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cousins',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='neices_and_nephews',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='siblings',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='spouse',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_upload_path),
        ),
    ]
