# Generated by Django 3.0.8 on 2020-08-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amount',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='A short paragraph or two that describes the recipe, including from whom or where you got it.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Modifcations, options, etc.', null=True),
        ),
    ]
