# Generated by Django 3.0.8 on 2020-08-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200807_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, help_text='Please use landscape photos.', null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('recipe', 'step_number')},
        ),
    ]
