# Generated by Django 3.0.8 on 2020-08-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['measurement']},
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='amount',
            field=models.CharField(help_text='e.g., 1/2, 3, 1 1/4, 12.5, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(help_text='Hold Ctrl + Click to enter multiple categories.', related_name='categories', to='recipes.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientlist',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
