# Generated by Django 3.0.8 on 2020-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200812_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='amount',
            field=models.CharField(help_text='1/2, 3, 1 1/4, 12.5, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='ingredient',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='measurement',
            field=models.CharField(help_text='Cup, tsp, tbsp, etc.', max_length=255),
        ),
    ]
