# Generated by Django 3.0.8 on 2020-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200813_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='amount',
            field=models.CharField(help_text='1/2, 3, 1 1/4, 12.5, etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='measurement',
            field=models.CharField(help_text='Cup, tsp, tbsp, large, etc.', max_length=255, null=True),
        ),
    ]
