# Generated by Django 3.0.8 on 2020-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200818_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientlist',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_published',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='amount',
            field=models.CharField(blank=True, help_text='1/2, 3, 1 1/4, 12.5, etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='measurement',
            field=models.CharField(blank=True, help_text='Cup, tsp, tbsp, large, etc.', max_length=255, null=True),
        ),
    ]
