# Generated by Django 3.0.8 on 2020-08-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200819_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date_published']},
        ),
    ]
