# Generated by Django 3.0.8 on 2020-08-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200819_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
