# Generated by Django 3.0.8 on 2020-09-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20200820_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientlist',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredientlist',
            name='measurement',
        ),
    ]
