# Generated by Django 3.0.8 on 2020-09-04 17:08

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20200903_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, help_text='Please use landscape photos.', null=True, upload_to=recipes.models.get_upload_path),
        ),
    ]
