# Generated by Django 3.1.1 on 2020-09-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_menu', '0004_auto_20200926_1050'),
        ('recipes', '0018_auto_20200925_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal_menu.storedepartment'),
        ),
    ]
