# Generated by Django 3.1.1 on 2020-09-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_menu', '0005_auto_20200930_1012'),
        ('recipes', '0019_ingredientlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='category',
            field=models.ForeignKey(help_text='Category is used to group shopping list items.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meal_menu.storedepartment'),
        ),
    ]
