# Generated by Django 3.1.1 on 2020-09-26 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20200925_1045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal_menu', '0002_auto_20200925_1351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together={('user', 'list_item', 'recipe')},
        ),
    ]
