# Generated by Django 3.1.1 on 2020-09-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_menu', '0003_auto_20200926_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_department', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Store Departments',
                'ordering': ['store_department'],
            },
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meal_menu.storedepartment'),
        ),
    ]
